# Generated by Django 2.2 on 2019-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(db_column='pid', primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(db_column='pname', max_length=150)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('owner_id', models.IntegerField(db_column='owner_id')),
                ('start_time', models.DateField(db_column='start_time', default=None)),
                ('end_time', models.DateField(db_column='end_time', default=None)),
                ('deadline', models.DateField(db_column='deadline', default=None)),
                ('is_public', models.BooleanField(db_column='is_public', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid')),
                ('gid', models.IntegerField(db_column='gid')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('sid', models.AutoField(db_column='sid', primary_key=True, serialize=False)),
                ('sname', models.CharField(db_column='sname', max_length=150)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('api_id', models.IntegerField(db_column='api_id', default=None)),
                ('priority', models.IntegerField(db_column='priority', default=5)),
                ('value', models.IntegerField(db_column='value', default=None)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time')),
                ('status', models.CharField(db_column='status', max_length=30)),
            ],
        ),
    ]
