# Generated by Django 2.2 on 2019-04-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190425_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(blank=True, db_column='end_time', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateField(blank=True, db_column='start_time', default=None, null=True),
        ),
    ]
